version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails-with-nginx
      MYSQL_USER: masashi
      MYSQL_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3307:3306"
  app:
    build: ./rails-with-nginx
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USER: masashi
      DB_NAME: rails-with-nginx
      DB_PASSWORD: password
      DB_HOST: db
    volumes:
      - ./rails-with-nginx:/rails-with-nginx
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build: ./nginx
    ports:
      - "8080:80"
    environment:
      NGINX_HOST: foobar.com
      NGINX_PORT: 80
    depends_on:
      - app
    volumes:
      - ./rails-with-nginx/log/nginx:/var/log/nginx